# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Minecraft / NeoForge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

neo_version=21.1.249
neo_version_range=[21,)

loader_version_range=[4,)


# Create
create_version=6.0.10-280
ponder_version=1.0.82
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67

# Mod
mod_id=create_tempratech
mod_name=Create_TempraTech
mod_license=All Rights Reserved
mod_version=1.0-SNAPSHOT
mod_group_id=Mods
mod_authors=
mod_description=